### PR TITLE
Migrate from connectivity to connectivity_plus

### PR DESCRIPTION
**Pull request by mnvr**
Both are official Flutter plugins. connectivity has been deprecated, and connectivity_plus is the replacement:

https://pub.dev/packages/connectivity_plus

## Test Plan

Tested on: iOS simulator, by turning WiFi on/off on the laptop

### CODE REVIEW

**Comment by ua741** [comment]
> Both are official Flutter plugins. connectivity has been deprecated, and connectivity_plus is the replacement:
> 
> https://pub.dev/packages/connectivity_plus
> ## Test Plan
> 
> Tested on: iOS simulator, by turning WiFi on/off on the laptop

The plugin has more connection state than previous plugins.
Should we treat VPN/Ethernet as Wifi or something else?

**Comment by mnvr** [comment]
> Should we treat VPN/Ethernet as Wifi or something else?

I think we should treat VPN/Ethernet as Wifi. But it is hard to say in a one-size-fits-all manner, open to alternatives too if you have reasons to think so.

**Comment by mnvr** [comment]
Thank you for the catch though! I've updated the PR.

**Comment by ua741** [comment]
Last time I was unable to build this on droid. Didn't spend much time. We are still facing the same issue. 

> flutter build apk --release --flavor independent

```
Because every version of flutter_test from sdk depends on meta 1.7.0 and connectivity_plus 3.0.2 depends on meta ^1.8.0, flutter_test from sdk is incompatible with connectivity_plus 3.0.2.
And because no versions of connectivity_plus match >3.0.2 <4.0.0, flutter_test from sdk is incompatible with connectivity_plus ^3.0.2.
So, because photos depends on both connectivity_plus ^3.0.2 and flutter_test from sdk, version solving failed.

```

**Comment by mnvr** [comment]
> Last time I was unable to build this on droid. Didn't spend much time. We are still facing the same issue.
> 
> >

Just saw this, for some reason GitHub didn't send me a mail about this.

`flutter build apk --release --flavor independent` works for me - I think it is because I'm on a newer Flutter (3.3.9). I think there is a pending task we have to update the Flutter version anyways, so we can try to merge this after that is done.

I've resolved the merge conflicts and pushed. Build is now failing for me, but it seems to be because of some other issue (`toastPosition`).

**Comment by mnvr** [comment]
Rebased off main

**Comment by mnvr** [comment]
Rebased this off main. Could you try again (now that we're on the updated Flutter, I think it should compile on Android too)?

**Comment by mnvr** [comment]
* I tried here, `flutter build apk --release --flavor independent` succeeded.
* Did a smoke test again on iOS simulator, that it is detecting connectivity changes, and I can upload files to a local museum

**Review by ua741 — APPROVED** [review]

**Pull request merged**
